version: "3"

networks:
  gqz.net:
    driver: bridge

services:
  api.webapp:
    image: canals/php:latest
    environment:
    - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
    - VHOST_DOCROOT=/var/www/api
    ports:
    - "58180:80"
    - "58343:443"
    volumes:
    - ./webapp_api/api:/var/www/api
    - ./webapp_api/src:/var/www/src
    working_dir: /var/www/src
    networks:
    - gqz.net
    links:
    - mysql.geoquizz:dbgeo

  api.backoffice:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "58181:80"
      - "58344:443"
    volumes :
      - ./backoffice_api/api:/var/www/api
      - ./backoffice_api/src:/var/www/src
    working_dir : /var/www/src
    networks:
      - gqz.net
    links :
      - mysql.geoquizz:dbgeo

  api.appli:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "58182:80"
      - "58345:443"
    volumes :
      - ./appli_api/api:/var/www/api
      - ./appli_api/src:/var/www/src
    working_dir : /var/www/src
    networks:
      - gqz.net
    links :
      - mysql.geoquizz:dbgeo

  mysql.geoquizz:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=geoquizz
      - MYSQL_USER=geoquizz
      - MYSQL_PASSWORD=geoquizz
      - MYSQL_DATABASE=geoquizz
    ports:
      - "58307:3306"
    networks:
      - gqz.net

  adminer:
     image: adminer
     ports:
       - "58080:8080"
     networks:
       - gqz.net
     links:
       - mysql.geoquizz:dbgeo
