version: "3"

networks:
  lbs.net:
    driver: bridge

services:
  api.webapp:
    image: canals/php:latest
    environment:
    - VHOST_HOSTNAME=api.webapp.local
    - VHOST_DOCROOT=/var/www/api
    ports:
    - "20080:80"
    - "20043:443"
    volumes:
    - ./webapp_api/api:/var/www/api
    - ./webapp_api/src:/var/www/src
    working_dir: /var/www/src
    networks:
    - lbs.net
    links:
    - mysql.commande:dbgeo

  api.backoffice:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.backoffice.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "21080:80"
      - "21043:443"
    volumes :
      - ./backoffice_api/api:/var/www/api
      - ./backoffice_api/src:/var/www/src
    working_dir : /var/www/src
    networks:
      - lbs.net
    links :
      - mysql.commande:dbgeo

  api.appli:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.appli.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "22080:80"
      - "22043:443"
    volumes :
      - ./appli_api/api:/var/www/api
      - ./appli_api/src:/var/www/src
    working_dir : /var/www/src
    networks:
      - lbs.net
    links :
      - mysql.commande:dbgeo


#############################
# mysql commande  + adminer
#############################
  mysql.commande:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=geoquizz
      - MYSQL_USER=geoquizz
      - MYSQL_PASSWORD=geoquizz
      - MYSQL_DATABASE=geoquizz
    ports:
      - "3307:3306"
    networks:
      - lbs.net
    volumes :
      - ./backoffice_api/sql:/var/sql
      - ./appli_api/sql:/var/sql
      - ./webapp_api/sql:/var/sql

  adminer:
     image: adminer
     ports:
       - "8080:8080"
     networks:
       - lbs.net
     links:
       - mysql.commande:dbgeo
